Repository terraform-providers/terraform-provider-cloudscale, pull requests merged in 2019-02, with the labels that each got.

#6 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  cloudscale/resource_cloudscale_floating_ip.go
  cloudscale/resource_cloudscale_server.go
Labels: size/XS

#8 Expose IP addresses as plain strings (fixes #7)
  CHANGELOG.md
  cloudscale/resource_cloudscale_server.go
  cloudscale/resource_cloudscale_server_test.go
  website/docs/r/server.html.markdown
Labels: documentation, size/M

#10 Use http status code for not found detection
  cloudscale/resource_cloudscale_floating_ip.go
  cloudscale/resource_cloudscale_server.go
  cloudscale/util.go
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/LICENSE
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/Makefile
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/README.md
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/cloudscale.go
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/metadata.go
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/metadata_json.go
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/servers.go
  vendor/github.com/cloudscale-ch/cloudscale-go-sdk/volumes.go
  vendor/vendor.json
Labels: dependencies, size/XL

#12 provider: Enable request/response logging
  cloudscale/config.go
Labels: enhancement, size/XS
